name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: cccm
            cross: false

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            exe: cccm
            cross: true

          - os: ubuntu-latest
            target: arm-unknown-linux-musleabi
            exe: cccm
            cross: true

          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            exe: cccm
            cross: true

          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            exe: cccm
            cross: true

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: cccm.exe
            cross: false

          - os: macos-latest
            target: x86_64-apple-darwin
            exe: cccm
            cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            exe: cccm
            cross: false

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          default: true

      - name: Install OpenSSL (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install pkg-config libssl-dev

      - name: Install OpenSSL (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install openssl@3
      
      # Native build
      - name: Install target
        if: matrix.cross == false
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        if: matrix.cross == false
        run: cargo build --release --target ${{ matrix.target }}

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross

      - name: Build release (cross)
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Run UPX
        # UPX may not support some platforms. Ignore the errors
        continue-on-error: true
        # Disable UPX for Windows and some ARM targets that may have issues
        if: matrix.os == 'ubuntu-latest' && !contains(matrix.target, 'windows') && !contains(matrix.target, 'arm')
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.2.2
          files: target/${{ matrix.target }}/release/${{ matrix.exe }}
          args: -q --best --lzma

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cccm-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.exe }}

      - name: Create release archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release/
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../cccm-${{ matrix.target }}.zip ${{ matrix.exe }}
          else
            tar czf ../../../cccm-${{ matrix.target }}.tar.gz ${{ matrix.exe }}
          fi

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cccm-${{ matrix.target }}.*
          generate_release_notes: true
          draft: false

  docker:
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/claude-code-config-manager
            ghcr.io/${{ github.repository_owner }}/claude-code-config-manager
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max